<?php
#
# Language list for gettext.wesnoth.org
#
# Translation statistics Web interface (gettext.wesnoth.org)
# Part of the Battle for Wesnoth Project <https://www.wesnoth.org/>
#

$langs = [
	'af'				=> 'Afrikaans',
	'ang'				=> 'Old English',
	'ang@latin'			=> 'Old English (Latin chars)',
	'ar'				=> 'Arabic',
	'ast'				=> 'Asturian',
	'bg'				=> 'Bulgarian',
	'ca'				=> 'Catalan',
	'ca_ES@valencia'	=> 'Valencian (southern Catalan)',
	'cs'				=> 'Czech',
	'da'				=> 'Danish',
	'de'				=> 'German',
	'es'				=> 'Spanish',
	'eu'				=> 'Basque',
	'fi'				=> 'Finnish',
	'fr'				=> 'French',
	'fur_IT'			=> 'Friulian',
	'el'				=> 'Greek',
	'en_GB'				=> 'British English',
	'en@shaw'			=> 'English (Shavian chars)',
	'eo'				=> 'Esperanto',
	'et'				=> 'Estonian',
	'ga'				=> 'Irish',
	'gd'				=> 'Scottish Gaelic',
	'gl'				=> 'Galician',
	'he'				=> 'Hebrew',
	'hr'				=> 'Croatian',
	'hu'				=> 'Hungarian',
	'id'				=> 'Indonesian',
	'is'				=> 'Icelandic',
	'it'				=> 'Italian',
	'ja'				=> 'Japanese',
	'ko'				=> 'Korean',
	'la'				=> 'Latin',
	'lt'				=> 'Lithuanian',
	'lv'				=> 'Latvian',
	'mk'				=> 'Macedonian',
	'mr'				=> 'Marathi',
	'nl'				=> 'Dutch',
	'nb_NO'				=> 'Norwegian',
	//'oc'				=> 'Occitan',
	'pl'				=> 'Polish',
	'pt'				=> 'Portuguese',
	'pt_BR'				=> 'Brazilian Portuguese',
	'racv'				=> 'RACV Language',
	'ro'				=> 'Romanian',
	'ru'				=> 'Russian',
	'sk'				=> 'Slovak',
	'sl'				=> 'Slovenian',
	'sr'				=> 'Serbian',
	'sv'				=> 'Swedish',
	'tl'				=> 'Filipino',
	'tr'				=> 'Turkish',
	'vi'				=> 'Vietnamese',
	'uk'				=> 'Ukrainian',
	'zh_CN'				=> 'Chinese',
	'zh_TW'				=> 'Chinese (Taiwan)',
];
